"""
THIS CODE WAS GENERATED BY AI.
"""
import random
from state import State

class RandomPlayer:
    def __init__(self, name, symbol):
        self.name = name
        self.symbol = symbol

    def choose_move(self, state):
        available_moves = state.get_legal_actions()
        if available_moves:
            return random.choice(available_moves)
        return None
